// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: address.sql

package db

import (
	"context"
)

const deleteUserAddress = `-- name: DeleteUserAddress :execrows
DELETE FROM "addresses"
WHERE "user_id" = $1
    AND "id" = $2
`

type DeleteUserAddressParams struct {
	UserID string `json:"user_id"`
	ID     string `json:"id"`
}

func (q *Queries) DeleteUserAddress(ctx context.Context, arg DeleteUserAddressParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserAddress, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const desableDefaultAddres = `-- name: DesableDefaultAddres :exec
UPDATE
    "addresses"
SET
    "is_default" = FALSE
WHERE
    "user_id" = $1
`

func (q *Queries) DesableDefaultAddres(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, desableDefaultAddres, userID)
	return err
}

const getAddressByUserID = `-- name: GetAddressByUserID :many
SELECT
    id, user_id, street_line_1, street_line_2, postal_code, state, city, country, is_default
FROM
    "addresses"
WHERE
    "user_id" = $1
`

func (q *Queries) GetAddressByUserID(ctx context.Context, userID string) ([]Address, error) {
	rows, err := q.db.Query(ctx, getAddressByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Address
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StreetLine1,
			&i.StreetLine2,
			&i.PostalCode,
			&i.State,
			&i.City,
			&i.Country,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAddress = `-- name: InsertAddress :exec
INSERT INTO "addresses" ("user_id", "street_line_1", "street_line_2", "postal_code", "state", "city", "country", "is_default")
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAddressParams struct {
	UserID      string  `json:"user_id"`
	StreetLine1 string  `json:"street_line_1"`
	StreetLine2 *string `json:"street_line_2"`
	PostalCode  string  `json:"postal_code"`
	State       string  `json:"state"`
	City        string  `json:"city"`
	Country     string  `json:"country"`
	IsDefault   bool    `json:"is_default"`
}

func (q *Queries) InsertAddress(ctx context.Context, arg InsertAddressParams) error {
	_, err := q.db.Exec(ctx, insertAddress,
		arg.UserID,
		arg.StreetLine1,
		arg.StreetLine2,
		arg.PostalCode,
		arg.State,
		arg.City,
		arg.Country,
		arg.IsDefault,
	)
	return err
}

const updateAddress = `-- name: UpdateAddress :exec
UPDATE
    "addresses"
SET
    "street_line_1" = COALESCE($3, "street_line_1"),
    "street_line_2" = COALESCE($4, "street_line_2"),
    "postal_code" = COALESCE($5, "postal_code"),
    "state" = COALESCE($6, "state"),
    "city" = COALESCE($7, "city"),
    "country" = COALESCE($8, "country")
WHERE
    "id" = $1
    AND "user_id" = $2
`

type UpdateAddressParams struct {
	ID          string  `json:"id"`
	UserID      string  `json:"user_id"`
	StreetLine1 *string `json:"street_line_1"`
	StreetLine2 *string `json:"street_line_2"`
	PostalCode  *string `json:"postal_code"`
	State       *string `json:"state"`
	City        *string `json:"city"`
	Country     *string `json:"country"`
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) error {
	_, err := q.db.Exec(ctx, updateAddress,
		arg.ID,
		arg.UserID,
		arg.StreetLine1,
		arg.StreetLine2,
		arg.PostalCode,
		arg.State,
		arg.City,
		arg.Country,
	)
	return err
}

const updateDefaultAddress = `-- name: UpdateDefaultAddress :execrows
UPDATE
    "addresses"
SET
    "is_default" = TRUE
WHERE
    "user_id" = $1
    AND "id" = $2
`

type UpdateDefaultAddressParams struct {
	UserID string `json:"user_id"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateDefaultAddress(ctx context.Context, arg UpdateDefaultAddressParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDefaultAddress, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
