// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cart.sql

package db

import (
	"context"
)

const deleteAllCartItem = `-- name: DeleteAllCartItem :execrows
DELETE FROM "cart_items" i USING "carts" c
WHERE i."cart_id" = $1 AND c."id" = i."cart_id" AND c."user_id" = $2
`

type DeleteAllCartItemParams struct {
	CartID string `json:"cart_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteAllCartItem(ctx context.Context, arg DeleteAllCartItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAllCartItem, arg.CartID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCart = `-- name: DeleteCart :execrows
DELETE FROM "carts" WHERE "id" = $1 AND "user_id" = $2
`

type DeleteCartParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteCart(ctx context.Context, arg DeleteCartParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCart, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCartItem = `-- name: DeleteCartItem :execrows
DELETE FROM "cart_items" i 
USING "carts" c 
WHERE i."id" = $1 AND c."id" = i."cart_id" AND c."user_id" = $2
`

type DeleteCartItemParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCartItem, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCartItemByID = `-- name: GetCartItemByID :one
SELECT id, cart_id, product_id, quantity, created_at, updated_at FROM "cart_items" WHERE "id" = $1
`

func (q *Queries) GetCartItemByID(ctx context.Context, id string) (CartItem, error) {
	row := q.db.QueryRow(ctx, getCartItemByID, id)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCart = `-- name: GetUserCart :one
SELECT
  c."id",
  COALESCE (
    (
      SELECT JSON_AGG(
        JSON_BUILD_OBJECT(
          'id', i."id",
          'product_id', p."id",
          'title', p."title",
          'price_in_cent', p."price_in_cent",
          'quantity', i."quantity"
        )
      )
      FROM "cart_items" i LEFT JOIN "products" p ON p."id" = i."product_id"
      WHERE i."cart_id" = c."id"
    ),'[]'::JSON
  ) AS "items"
FROM "carts" c WHERE c."user_id" = $1
`

type GetUserCartRow struct {
	ID    string      `json:"id"`
	Items interface{} `json:"items"`
}

func (q *Queries) GetUserCart(ctx context.Context, userID string) (GetUserCartRow, error) {
	row := q.db.QueryRow(ctx, getUserCart, userID)
	var i GetUserCartRow
	err := row.Scan(&i.ID, &i.Items)
	return i, err
}

const insertCart = `-- name: InsertCart :one
INSERT INTO "carts"("user_id") VALUES ($1)
ON CONFLICT ("user_id") DO UPDATE SET "user_id" = EXCLUDED."user_id"
RETURNING "id"
`

func (q *Queries) InsertCart(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRow(ctx, insertCart, userID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertCartItem = `-- name: InsertCartItem :one
INSERT INTO "cart_items"("cart_id", "product_id", "quantity")
VALUES ($1, $2, $3) ON CONFLICT ("cart_id", "product_id")
DO UPDATE SET "quantity" = EXCLUDED."quantity" + "cart_items"."quantity"
RETURNING "id"
`

type InsertCartItemParams struct {
	CartID    string `json:"cart_id"`
	ProductID string `json:"product_id"`
	Quantity  int32  `json:"quantity"`
}

func (q *Queries) InsertCartItem(ctx context.Context, arg InsertCartItemParams) (string, error) {
	row := q.db.QueryRow(ctx, insertCartItem, arg.CartID, arg.ProductID, arg.Quantity)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :execrows
UPDATE "cart_items" i SET "quantity" = $1, "updated_at" = NOW()
FROM "carts" c WHERE i."id" = $2 AND c."id" = i."cart_id" AND c."user_id" = $3
`

type UpdateCartItemQuantityParams struct {
	Quantity int32  `json:"quantity"`
	ID       string `json:"id"`
	UserID   string `json:"user_id"`
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCartItemQuantity, arg.Quantity, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
