// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: home.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPopularProducts = `-- name: GetPopularProducts :many
SELECT
    p."id",
    p."title",
    p."price_in_cent",
    p."stock",
    i."image_url",
    ROUND(AVG(r."rating"), 2) AS "rating"
FROM
    "products" p
    LEFT JOIN "reviews" r ON r."product_id" = p."id"
    LEFT JOIN LATERAL (
        SELECT
            "image_url"
        FROM
            "product_images"
        WHERE
            "product_id" = p."id"
            AND "is_default" = TRUE
        LIMIT 1) i ON TRUE
WHERE
    "rating" > 3.5
`

type GetPopularProductsRow struct {
	ID          string         `json:"id"`
	Title       string         `json:"title"`
	PriceInCent int32          `json:"price_in_cent"`
	Stock       int32          `json:"stock"`
	ImageUrl    string         `json:"image_url"`
	Rating      pgtype.Numeric `json:"rating"`
}

func (q *Queries) GetPopularProducts(ctx context.Context) ([]GetPopularProductsRow, error) {
	rows, err := q.db.Query(ctx, getPopularProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPopularProductsRow
	for rows.Next() {
		var i GetPopularProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.PriceInCent,
			&i.Stock,
			&i.ImageUrl,
			&i.Rating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProducts = `-- name: GetProducts :many
SELECT
    p."id",
    p."title",
    p."price_in_cent",
    p."stock",
    i."image_url"
FROM
    "products" p
    LEFT JOIN "categories" c ON c."id" = p."category_id"
    LEFT JOIN LATERAL (
        SELECT
            "image_url"
        FROM
            "product_images"
        WHERE
            "product_id" = p."id"
            AND "is_default" = TRUE
        LIMIT 1) i ON TRUE
WHERE ($1::text IS NULL
    OR p.title ILIKE '%' || $1::text || '%')
AND ($2::text IS NULL
    OR c.slug = $2)
AND ($3::numeric IS NULL
    OR p.price_in_cent >= $3)
AND ($4::numeric IS NULL
    OR p.price_in_cent <= $4)
ORDER BY
    CASE WHEN $5::text = 'price_asc' THEN
        p.price_in_cent
    END ASC,
    CASE WHEN $5::text = 'price_desc' THEN
        p.price_in_cent
    END DESC,
    CASE WHEN $5::text = 'name_asc' THEN
        p.title
    END ASC,
    p.id DESC
`

type GetProductsParams struct {
	Search   *string        `json:"search"`
	Slug     *string        `json:"slug"`
	MinPrice pgtype.Numeric `json:"min_price"`
	MaxPrice pgtype.Numeric `json:"max_price"`
	SortBy   *string        `json:"sort_by"`
}

type GetProductsRow struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	PriceInCent int32  `json:"price_in_cent"`
	Stock       int32  `json:"stock"`
	ImageUrl    string `json:"image_url"`
}

func (q *Queries) GetProducts(ctx context.Context, arg GetProductsParams) ([]GetProductsRow, error) {
	rows, err := q.db.Query(ctx, getProducts,
		arg.Search,
		arg.Slug,
		arg.MinPrice,
		arg.MaxPrice,
		arg.SortBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsRow
	for rows.Next() {
		var i GetProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.PriceInCent,
			&i.Stock,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsCategory = `-- name: GetProductsCategory :many
SELECT
    id, name, slug, created_at
FROM
    "categories"
LIMIT $1
`

func (q *Queries) GetProductsCategory(ctx context.Context, limit int32) ([]Category, error) {
	rows, err := q.db.Query(ctx, getProductsCategory, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
