// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: image.sql

package db

import (
	"context"
)

const deleteProductImage = `-- name: DeleteProductImage :exec
DELETE FROM "product_images" i USING "products" p
WHERE i."id" = $1
    AND i."product_id" = p."id"
    AND p."user_id" = $2
`

type DeleteProductImageParams struct {
	ID     string `json:"id"`
	UserID string `json:"-"`
}

func (q *Queries) DeleteProductImage(ctx context.Context, arg DeleteProductImageParams) error {
	_, err := q.db.Exec(ctx, deleteProductImage, arg.ID, arg.UserID)
	return err
}

const getDefaultImageID = `-- name: GetDefaultImageID :one
SELECT
    "id"
FROM
    "product_images"
WHERE
    "product_id" = $1
    AND "is_default" = TRUE
`

func (q *Queries) GetDefaultImageID(ctx context.Context, productID string) (string, error) {
	row := q.db.QueryRow(ctx, getDefaultImageID, productID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getProductImages = `-- name: GetProductImages :one
SELECT
    "image_url",
    "is_default"
FROM
    "product_images"
WHERE
    "product_id" = $1
    AND "id" = $2
`

type GetProductImagesParams struct {
	ProductID string `json:"product_id"`
	ID        string `json:"id"`
}

type GetProductImagesRow struct {
	ImageUrl  string `json:"image_url"`
	IsDefault bool   `json:"is_default"`
}

func (q *Queries) GetProductImages(ctx context.Context, arg GetProductImagesParams) (GetProductImagesRow, error) {
	row := q.db.QueryRow(ctx, getProductImages, arg.ProductID, arg.ID)
	var i GetProductImagesRow
	err := row.Scan(&i.ImageUrl, &i.IsDefault)
	return i, err
}

const insertProductImage = `-- name: InsertProductImage :exec
INSERT INTO "product_images" ("product_id", "image_url", "is_default")
    VALUES ($1, $2, $3)
`

type InsertProductImageParams struct {
	ProductID string `json:"product_id"`
	ImageUrl  string `json:"image_url"`
	IsDefault bool   `json:"is_default"`
}

func (q *Queries) InsertProductImage(ctx context.Context, arg InsertProductImageParams) error {
	_, err := q.db.Exec(ctx, insertProductImage, arg.ProductID, arg.ImageUrl, arg.IsDefault)
	return err
}

const updateDefaultImage = `-- name: UpdateDefaultImage :execrows
UPDATE
    "product_images"
SET
    "is_default" = $1
WHERE
    "id" = $2
`

type UpdateDefaultImageParams struct {
	IsDefault bool   `json:"is_default"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateDefaultImage(ctx context.Context, arg UpdateDefaultImageParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDefaultImage, arg.IsDefault, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
