// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID          string  `json:"id"`
	UserID      string  `json:"user_id"`
	StreetLine1 string  `json:"street_line_1"`
	StreetLine2 *string `json:"street_line_2"`
	PostalCode  string  `json:"postal_code"`
	State       string  `json:"state"`
	City        string  `json:"city"`
	Country     string  `json:"country"`
	IsDefault   bool    `json:"is_default"`
}

type Cart struct {
	ID        string           `json:"id"`
	UserID    string           `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type CartItem struct {
	ID        string           `json:"id"`
	CartID    string           `json:"cart_id"`
	ProductID string           `json:"product_id"`
	Quantity  int32            `json:"quantity"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Category struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Slug      string           `json:"slug"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Order struct {
	ID              string           `json:"id"`
	UserID          string           `json:"user_id"`
	AddressID       string           `json:"address_id"`
	ShipPriceInCent int32            `json:"ship_price_in_cent"`
	Status          string           `json:"status"`
	ShipDate        pgtype.Date      `json:"ship_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type OrderItem struct {
	ID        string `json:"id"`
	OrderID   string `json:"order_id"`
	ProductID string `json:"product_id"`
	Quantity  int32  `json:"quantity"`
}

type Payment struct {
	ID             string           `json:"id"`
	UserID         string           `json:"user_id"`
	TransactionID  string           `json:"transaction_id"`
	Status         string           `json:"status"`
	OrderID        string           `json:"order_id"`
	PaymentGateway string           `json:"payment_gateway"`
	AmountInCent   int32            `json:"amount_in_cent"`
	Currency       string           `json:"currency"`
	PaymentMethod  string           `json:"payment_method"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type Product struct {
	ID          string           `json:"id"`
	UserID      string           `json:"-"`
	Title       string           `json:"title"`
	PriceInCent int32            `json:"price_in_cent"`
	Stock       int32            `json:"stock"`
	CategoryID  string           `json:"category_id"`
	Description *string          `json:"description"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type ProductImage struct {
	ID        string `json:"id"`
	ProductID string `json:"product_id"`
	ImageUrl  string `json:"image_url"`
	IsDefault bool   `json:"is_default"`
}

type RefreshToken struct {
	ID         string      `json:"id"`
	UserID     string      `json:"user_id"`
	HashToken  string      `json:"hash_token"`
	ExpiaredAt pgtype.Date `json:"expiared_at"`
}

type Review struct {
	ID        string           `json:"id"`
	UserID    string           `json:"user_id"`
	ProductID string           `json:"product_id"`
	Rating    int32            `json:"rating"`
	Comment   *string          `json:"comment"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID           string           `json:"id"`
	FullName     string           `json:"full_name"`
	Birth        pgtype.Date      `json:"birth"`
	Phone        string           `json:"phone"`
	Email        string           `json:"email"`
	HashPassword string           `json:"-"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
