// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserOrder = `-- name: DeleteUserOrder :exec
DELETE FROM "orders"
WHERE "id" = $1
    AND "user_id" = $2
`

type DeleteUserOrderParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteUserOrder(ctx context.Context, arg DeleteUserOrderParams) error {
	_, err := q.db.Exec(ctx, deleteUserOrder, arg.ID, arg.UserID)
	return err
}

const getAllUserOrders = `-- name: GetAllUserOrders :many
SELECT
    o."id",
    o."ship_date",
    o."status",
    o."ship_price_in_cent",
    o."created_at",
    COALESCE((
        SELECT
            ROW_TO_JSON(a_sub)
        FROM (
            SELECT
                a."street_line_1", a."street_line_2", a."postal_code", a."state", a."city", a."country"
            FROM "addresses" a
            WHERE
                a."id" = o."address_id") a_sub), '{}'::json) AS "address",
    COALESCE((
        SELECT
            JSON_AGG(JSON_BUILD_OBJECT('id', i."id", 'title', p."title", 'stock', p."stock", 'quantity', i.quantity))
        FROM "order_items" i
    LEFT JOIN "products" p ON p."id" = i."product_id"
    WHERE
        i."order_id" = o."id"), '[]'::json) AS "order_items"
FROM
    "orders" o
WHERE
    o."user_id" = $1
`

type GetAllUserOrdersRow struct {
	ID              string           `json:"id"`
	ShipDate        pgtype.Date      `json:"ship_date"`
	Status          string           `json:"status"`
	ShipPriceInCent int32            `json:"ship_price_in_cent"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	Address         interface{}      `json:"address"`
	OrderItems      interface{}      `json:"order_items"`
}

func (q *Queries) GetAllUserOrders(ctx context.Context, userID string) ([]GetAllUserOrdersRow, error) {
	rows, err := q.db.Query(ctx, getAllUserOrders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUserOrdersRow
	for rows.Next() {
		var i GetAllUserOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.ShipDate,
			&i.Status,
			&i.ShipPriceInCent,
			&i.CreatedAt,
			&i.Address,
			&i.OrderItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnpayedOrder = `-- name: GetUnpayedOrder :one
SELECT
    o."id",
    o."ship_price_in_cent",
    COALESCE((
        SELECT
            JSON_AGG(JSON_BUILD_OBJECT('id', i."id", 'product_id', p."id", 'price_in_cent', p."price_in_cent", 'quantity', i.quantity))
        FROM "order_items" i
    LEFT JOIN "products" p ON p."id" = i."product_id"
    WHERE
        i."order_id" = o."id"), '[]'::json) AS "order_items"
FROM
    "orders" o
WHERE
    o."user_id" = $1
    AND "status" = 'pending'
`

type GetUnpayedOrderRow struct {
	ID              string      `json:"id"`
	ShipPriceInCent int32       `json:"ship_price_in_cent"`
	OrderItems      interface{} `json:"order_items"`
}

func (q *Queries) GetUnpayedOrder(ctx context.Context, userID string) (GetUnpayedOrderRow, error) {
	row := q.db.QueryRow(ctx, getUnpayedOrder, userID)
	var i GetUnpayedOrderRow
	err := row.Scan(&i.ID, &i.ShipPriceInCent, &i.OrderItems)
	return i, err
}

const getUserOrder = `-- name: GetUserOrder :one
SELECT
    o."id",
    o."ship_date",
    o."status",
    o."ship_price_in_cent",
    o."created_at",
    COALESCE((
        SELECT
            ROW_TO_JSON(a_sub)
        FROM (
            SELECT
                a."street_line_1", a."street_line_2", a."postal_code", a."state", a."city", a."country"
            FROM "addresses" a
            WHERE
                a."id" = o."address_id") a_sub), '{}'::json) AS "address",
    COALESCE((
        SELECT
            JSON_AGG(JSON_BUILD_OBJECT('id', i."id", 'title', p."title", 'stock', p."stock", 'quantity', i.quantity))
        FROM "order_items" i
    LEFT JOIN "products" p ON p."id" = i."product_id"
    WHERE
        i."order_id" = o."id"), '[]'::json) AS "order_items"
FROM
    "orders" o
WHERE
    o."user_id" = $1
    AND o."id" = $2
`

type GetUserOrderParams struct {
	UserID string `json:"user_id"`
	ID     string `json:"id"`
}

type GetUserOrderRow struct {
	ID              string           `json:"id"`
	ShipDate        pgtype.Date      `json:"ship_date"`
	Status          string           `json:"status"`
	ShipPriceInCent int32            `json:"ship_price_in_cent"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	Address         interface{}      `json:"address"`
	OrderItems      interface{}      `json:"order_items"`
}

func (q *Queries) GetUserOrder(ctx context.Context, arg GetUserOrderParams) (GetUserOrderRow, error) {
	row := q.db.QueryRow(ctx, getUserOrder, arg.UserID, arg.ID)
	var i GetUserOrderRow
	err := row.Scan(
		&i.ID,
		&i.ShipDate,
		&i.Status,
		&i.ShipPriceInCent,
		&i.CreatedAt,
		&i.Address,
		&i.OrderItems,
	)
	return i, err
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO "orders" ("user_id", "address_id", "ship_date", "ship_price_in_cent")
    VALUES ($1, $2, $3, $4)
RETURNING
    "id"
`

type InsertOrderParams struct {
	UserID          string      `json:"user_id"`
	AddressID       string      `json:"address_id"`
	ShipDate        pgtype.Date `json:"ship_date"`
	ShipPriceInCent int32       `json:"ship_price_in_cent"`
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (string, error) {
	row := q.db.QueryRow(ctx, insertOrder,
		arg.UserID,
		arg.AddressID,
		arg.ShipDate,
		arg.ShipPriceInCent,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertOrderItem = `-- name: InsertOrderItem :exec
INSERT INTO "order_items" ("order_id", "product_id", "quantity")
    VALUES ($1, $2, $3)
`

type InsertOrderItemParams struct {
	OrderID   string `json:"order_id"`
	ProductID string `json:"product_id"`
	Quantity  int32  `json:"quantity"`
}

func (q *Queries) InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) error {
	_, err := q.db.Exec(ctx, insertOrderItem, arg.OrderID, arg.ProductID, arg.Quantity)
	return err
}
