// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getExpiredPendingPayments = `-- name: GetExpiredPendingPayments :many
SELECT
    id, user_id, transaction_id, status, order_id, payment_gateway, amount_in_cent, currency, payment_method, created_at
FROM
    "payments"
WHERE
    "status" = 'pending'
    AND "created_at" < $1
`

func (q *Queries) GetExpiredPendingPayments(ctx context.Context, createdAt pgtype.Timestamp) ([]Payment, error) {
	rows, err := q.db.Query(ctx, getExpiredPendingPayments, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TransactionID,
			&i.Status,
			&i.OrderID,
			&i.PaymentGateway,
			&i.AmountInCent,
			&i.Currency,
			&i.PaymentMethod,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT
    id, user_id, transaction_id, status, order_id, payment_gateway, amount_in_cent, currency, payment_method, created_at
FROM
    "payments"
WHERE
    "id" = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TransactionID,
		&i.Status,
		&i.OrderID,
		&i.PaymentGateway,
		&i.AmountInCent,
		&i.Currency,
		&i.PaymentMethod,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByOrder = `-- name: GetPaymentByOrder :one
SELECT
    id, user_id, transaction_id, status, order_id, payment_gateway, amount_in_cent, currency, payment_method, created_at
FROM
    "payments"
WHERE
    "order_id" = $1
    AND "user_id" = $2
`

type GetPaymentByOrderParams struct {
	OrderID string `json:"order_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) GetPaymentByOrder(ctx context.Context, arg GetPaymentByOrderParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByOrder, arg.OrderID, arg.UserID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TransactionID,
		&i.Status,
		&i.OrderID,
		&i.PaymentGateway,
		&i.AmountInCent,
		&i.Currency,
		&i.PaymentMethod,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByTransaction = `-- name: GetPaymentByTransaction :one
SELECT
    id, user_id, transaction_id, status, order_id, payment_gateway, amount_in_cent, currency, payment_method, created_at
FROM
    "payments"
WHERE
    "transaction_id" = $1
`

func (q *Queries) GetPaymentByTransaction(ctx context.Context, transactionID string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByTransaction, transactionID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TransactionID,
		&i.Status,
		&i.OrderID,
		&i.PaymentGateway,
		&i.AmountInCent,
		&i.Currency,
		&i.PaymentMethod,
		&i.CreatedAt,
	)
	return i, err
}

const insertPayment = `-- name: InsertPayment :one
INSERT INTO "payments" ("user_id", "transaction_id", "status", "order_id", "payment_gateway", "amount_in_cent", "currency", "payment_method")
    VALUES ($1, $2, 'pending', $3, $4, $5, $6, $7)
RETURNING
    "id", "user_id", "transaction_id", "status", "order_id", "payment_gateway", "amount_in_cent", "currency", "payment_method", "created_at"
`

type InsertPaymentParams struct {
	UserID         string `json:"user_id"`
	TransactionID  string `json:"transaction_id"`
	OrderID        string `json:"order_id"`
	PaymentGateway string `json:"payment_gateway"`
	AmountInCent   int32  `json:"amount_in_cent"`
	Currency       string `json:"currency"`
	PaymentMethod  string `json:"payment_method"`
}

func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, insertPayment,
		arg.UserID,
		arg.TransactionID,
		arg.OrderID,
		arg.PaymentGateway,
		arg.AmountInCent,
		arg.Currency,
		arg.PaymentMethod,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TransactionID,
		&i.Status,
		&i.OrderID,
		&i.PaymentGateway,
		&i.AmountInCent,
		&i.Currency,
		&i.PaymentMethod,
		&i.CreatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :execrows
UPDATE "orders"
SET
    "status" = $1
WHERE
    "id" = $2
    AND "user_id" = $3
`

type UpdateOrderStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOrderStatus, arg.Status, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :execrows
UPDATE "payments"
SET
    "status" = $1
WHERE
    "id" = $2
    AND "status" = 'pending'
`

type UpdatePaymentStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePaymentStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
