// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProductByUserID = `-- name: GetProductByUserID :one
SELECT
    p."id",
    p."title",
    p."price_in_cent",
    p."stock",
    p."description",
    COALESCE((
        SELECT
            ROW_TO_JSON(c_sub)
        FROM (
            SELECT
                c."id", c."name", c."slug"
            FROM "categories" c
            WHERE
                c."id" = p."category_id") c_sub), '{}'::json) AS "category",
    COALESCE((
        SELECT
            JSON_AGG(JSON_BUILD_OBJECT('id', i."id", 'image_url', i."image_url", 'is_default', i."is_default"))
        FROM "product_images" i
        WHERE
            i."product_id" = p."id"), '[]'::json) AS "image_url",
    COALESCE((
        SELECT
            JSON_AGG(JSON_BUILD_OBJECT('id', r."id", 'rating', r."rating", 'comment', r."comment", 'created_at', r."created_at"))
        FROM "reviews" r
        WHERE
            r."product_id" = p."id"), '[]'::json) AS "reviews"
FROM
    "products" p
WHERE
    p."id" = $1
    AND p."user_id" = $2
    AND "deleted_at" IS NULL
`

type GetProductByUserIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"-"`
}

type GetProductByUserIDRow struct {
	ID          string      `json:"id"`
	Title       string      `json:"title"`
	PriceInCent int32       `json:"price_in_cent"`
	Stock       int32       `json:"stock"`
	Description *string     `json:"description"`
	Category    interface{} `json:"category"`
	ImageUrl    interface{} `json:"image_url"`
	Reviews     interface{} `json:"reviews"`
}

func (q *Queries) GetProductByUserID(ctx context.Context, arg GetProductByUserIDParams) (GetProductByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByUserID, arg.ID, arg.UserID)
	var i GetProductByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.PriceInCent,
		&i.Stock,
		&i.Description,
		&i.Category,
		&i.ImageUrl,
		&i.Reviews,
	)
	return i, err
}

const getProductDetails = `-- name: GetProductDetails :one
SELECT
    p."id",
    p."title",
    p."price_in_cent",
    p."stock",
    p."description",
    c."name" AS "category_name",
    COALESCE((
        SELECT
            JSON_AGG(JSON_BUILD_OBJECT('id', r."id", 'user_id', r."user_id", 'rating', r."rating", 'comment', r."comment"))
        FROM "reviews" r
        WHERE
            r."product_id" = p."id"), '[]'::json) AS "review",
    COALESCE((
        SELECT
            JSON_AGG(i."image_url")
        FROM "product_images" i
        WHERE
            i."product_id" = p."id"), '[]'::json) AS "image_url"
FROM
    "products" p
    LEFT JOIN "categories" c ON c."id" = p."category_id"
WHERE
    p."id" = $1
    AND "deleted_at" IS NULL
`

type GetProductDetailsRow struct {
	ID           string      `json:"id"`
	Title        string      `json:"title"`
	PriceInCent  int32       `json:"price_in_cent"`
	Stock        int32       `json:"stock"`
	Description  *string     `json:"description"`
	CategoryName *string     `json:"category_name"`
	Review       interface{} `json:"review"`
	ImageUrl     interface{} `json:"image_url"`
}

func (q *Queries) GetProductDetails(ctx context.Context, id string) (GetProductDetailsRow, error) {
	row := q.db.QueryRow(ctx, getProductDetails, id)
	var i GetProductDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.PriceInCent,
		&i.Stock,
		&i.Description,
		&i.CategoryName,
		&i.Review,
		&i.ImageUrl,
	)
	return i, err
}

const getProductRating = `-- name: GetProductRating :one
SELECT
    ROUND(AVG("rating"), 2) AS "average_rating"
FROM
    "reviews" r
WHERE
    r."product_id" = $1
GROUP BY
    r."product_id"
`

func (q *Queries) GetProductRating(ctx context.Context, productID string) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getProductRating, productID)
	var average_rating pgtype.Numeric
	err := row.Scan(&average_rating)
	return average_rating, err
}

const getProductStock = `-- name: GetProductStock :one
SELECT
    "stock"
FROM
    "products"
WHERE
    "id" = $1
`

func (q *Queries) GetProductStock(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, getProductStock, id)
	var stock int32
	err := row.Scan(&stock)
	return stock, err
}

const getProductsByUserID = `-- name: GetProductsByUserID :many
SELECT
    p."id",
    p."title",
    p."price_in_cent",
    p."stock",
    p."description",
    COALESCE((
        SELECT
            ROW_TO_JSON(c_sub)
        FROM (
            SELECT
                c."id", c."name", c."slug"
            FROM "categories" c
            WHERE
                c."id" = p."category_id") c_sub), '{}'::json) AS "category",
    COALESCE((
        SELECT
            JSON_AGG(i."image_url")
        FROM "product_images" i
        WHERE
            i."product_id" = p."id"), '[]'::json) AS "image_url",
    COALESCE((
        SELECT
            JSON_AGG(JSON_BUILD_OBJECT('id', r."id", 'rating', r."rating", 'comment', r."comment", 'created_at', r."created_at"))
        FROM "reviews" r
        WHERE
            r."product_id" = p."id"), '[]'::json) AS "reviews"
FROM
    "products" p
WHERE
    p."user_id" = $1
    AND "deleted_at" IS NULL
`

type GetProductsByUserIDRow struct {
	ID          string      `json:"id"`
	Title       string      `json:"title"`
	PriceInCent int32       `json:"price_in_cent"`
	Stock       int32       `json:"stock"`
	Description *string     `json:"description"`
	Category    interface{} `json:"category"`
	ImageUrl    interface{} `json:"image_url"`
	Reviews     interface{} `json:"reviews"`
}

func (q *Queries) GetProductsByUserID(ctx context.Context, userID string) ([]GetProductsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getProductsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsByUserIDRow
	for rows.Next() {
		var i GetProductsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.PriceInCent,
			&i.Stock,
			&i.Description,
			&i.Category,
			&i.ImageUrl,
			&i.Reviews,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCategory = `-- name: InsertCategory :one
INSERT INTO "categories" ("name", "slug")
    VALUES ($1, $2)
ON CONFLICT ("slug")
    DO UPDATE SET
        "name" = EXCLUDED."name"
    RETURNING
        "id"
`

type InsertCategoryParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) (string, error) {
	row := q.db.QueryRow(ctx, insertCategory, arg.Name, arg.Slug)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO "products" ("title", "user_id", "price_in_cent", "stock", "category_id", "description")
    VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    "id"
`

type InsertProductParams struct {
	Title       string  `json:"title"`
	UserID      string  `json:"-"`
	PriceInCent int32   `json:"price_in_cent"`
	Stock       int32   `json:"stock"`
	CategoryID  string  `json:"category_id"`
	Description *string `json:"description"`
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (string, error) {
	row := q.db.QueryRow(ctx, insertProduct,
		arg.Title,
		arg.UserID,
		arg.PriceInCent,
		arg.Stock,
		arg.CategoryID,
		arg.Description,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const softDeleteProduct = `-- name: SoftDeleteProduct :execrows
UPDATE
    "products"
SET
    "deleted_at" = NOW()
WHERE
    "id" = $1
    AND "user_id" = $2
    AND "deleted_at" IS NULL
`

type SoftDeleteProductParams struct {
	ID     string `json:"id"`
	UserID string `json:"-"`
}

func (q *Queries) SoftDeleteProduct(ctx context.Context, arg SoftDeleteProductParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProduct, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE
    "products"
SET
    "title" = COALESCE($3, "title"),
    "price_in_cent" = COALESCE($4, "price_in_cent"),
    "stock" = COALESCE($5, "stock"),
    "description" = COALESCE($6, "description"),
    "category_id" = COALESCE($7, "category_id"),
    "updated_at" = NOW()
WHERE
    "id" = $1
    AND "user_id" = $2
    AND "deleted_at" IS NULL
`

type UpdateProductParams struct {
	ID          string      `json:"id"`
	UserID      string      `json:"-"`
	Title       *string     `json:"title"`
	PriceInCent *int32      `json:"price_in_cent"`
	Stock       *int32      `json:"stock"`
	Description *string     `json:"description"`
	CategoryID  pgtype.UUID `json:"category_id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.Exec(ctx, updateProduct,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.PriceInCent,
		arg.Stock,
		arg.Description,
		arg.CategoryID,
	)
	return err
}

const updateProductStock = `-- name: UpdateProductStock :exec
UPDATE
    "products"
SET
    "stock" = $1
WHERE
    "id" = $2
`

type UpdateProductStockParams struct {
	Stock int32  `json:"stock"`
	ID    string `json:"id"`
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) error {
	_, err := q.db.Exec(ctx, updateProductStock, arg.Stock, arg.ID)
	return err
}
