// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review.sql

package db

import (
	"context"
)

const getProductReviews = `-- name: GetProductReviews :many
SELECT
    "id",
    "user_id",
    "rating",
    "comment"
FROM
    "reviews"
WHERE
    "product_id" = $1
    AND "comment" IS NOT NULL
`

type GetProductReviewsRow struct {
	ID      string  `json:"id"`
	UserID  string  `json:"user_id"`
	Rating  int32   `json:"rating"`
	Comment *string `json:"comment"`
}

func (q *Queries) GetProductReviews(ctx context.Context, productID string) ([]GetProductReviewsRow, error) {
	rows, err := q.db.Query(ctx, getProductReviews, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductReviewsRow
	for rows.Next() {
		var i GetProductReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Rating,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT
    "id",
    "rating",
    "comment"
FROM
    "reviews"
WHERE
    "id" = $1
`

type GetReviewByIDRow struct {
	ID      string  `json:"id"`
	Rating  int32   `json:"rating"`
	Comment *string `json:"comment"`
}

func (q *Queries) GetReviewByID(ctx context.Context, id string) (GetReviewByIDRow, error) {
	row := q.db.QueryRow(ctx, getReviewByID, id)
	var i GetReviewByIDRow
	err := row.Scan(&i.ID, &i.Rating, &i.Comment)
	return i, err
}

const getUserReview = `-- name: GetUserReview :one
SELECT
    "id",
    "rating",
    "comment"
FROM
    "reviews"
WHERE
    "user_id" = $1
    AND "product_id" = $2
`

type GetUserReviewParams struct {
	UserID    string `json:"user_id"`
	ProductID string `json:"product_id"`
}

type GetUserReviewRow struct {
	ID      string  `json:"id"`
	Rating  int32   `json:"rating"`
	Comment *string `json:"comment"`
}

func (q *Queries) GetUserReview(ctx context.Context, arg GetUserReviewParams) (GetUserReviewRow, error) {
	row := q.db.QueryRow(ctx, getUserReview, arg.UserID, arg.ProductID)
	var i GetUserReviewRow
	err := row.Scan(&i.ID, &i.Rating, &i.Comment)
	return i, err
}

const insertReview = `-- name: InsertReview :one
INSERT INTO "reviews" ("user_id", "product_id", "rating", "comment")
    VALUES ($1, $2, $3, $4)
RETURNING
    "id"
`

type InsertReviewParams struct {
	UserID    string  `json:"user_id"`
	ProductID string  `json:"product_id"`
	Rating    int32   `json:"rating"`
	Comment   *string `json:"comment"`
}

func (q *Queries) InsertReview(ctx context.Context, arg InsertReviewParams) (string, error) {
	row := q.db.QueryRow(ctx, insertReview,
		arg.UserID,
		arg.ProductID,
		arg.Rating,
		arg.Comment,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
