// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestReviews = `-- name: GetLatestReviews :many
SELECT
    r."id",
    r."rating",
    r."comment",
    r."created_at",
    r."product_id",
    p."title" AS "product_title",
    i."image_url"
FROM
    "reviews" r
    JOIN "products" p ON p."id" = r."product_id"
    LEFT JOIN LATERAL (
        SELECT
            "image_url"
        FROM
            "product_images"
        WHERE
            "product_id" = p."id"
            AND "is_default" = TRUE
        LIMIT 1) i ON TRUE
WHERE
    r."comment" IS NOT NULL
ORDER BY
    r."created_at" DESC
LIMIT $1
`

type GetLatestReviewsRow struct {
	ID           string           `json:"id"`
	Rating       int32            `json:"rating"`
	Comment      *string          `json:"comment"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	ProductID    string           `json:"product_id"`
	ProductTitle string           `json:"product_title"`
	ImageUrl     string           `json:"image_url"`
}

func (q *Queries) GetLatestReviews(ctx context.Context, limit int32) ([]GetLatestReviewsRow, error) {
	rows, err := q.db.Query(ctx, getLatestReviews, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestReviewsRow
	for rows.Next() {
		var i GetLatestReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.ProductID,
			&i.ProductTitle,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductReviews = `-- name: GetProductReviews :many
SELECT
    "id",
    "user_id",
    "rating",
    "comment"
FROM
    "reviews"
WHERE
    "product_id" = $1
    AND "comment" IS NOT NULL
`

type GetProductReviewsRow struct {
	ID      string  `json:"id"`
	UserID  string  `json:"user_id"`
	Rating  int32   `json:"rating"`
	Comment *string `json:"comment"`
}

func (q *Queries) GetProductReviews(ctx context.Context, productID string) ([]GetProductReviewsRow, error) {
	rows, err := q.db.Query(ctx, getProductReviews, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductReviewsRow
	for rows.Next() {
		var i GetProductReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Rating,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT
    "id",
    "rating",
    "comment"
FROM
    "reviews"
WHERE
    "id" = $1
`

type GetReviewByIDRow struct {
	ID      string  `json:"id"`
	Rating  int32   `json:"rating"`
	Comment *string `json:"comment"`
}

func (q *Queries) GetReviewByID(ctx context.Context, id string) (GetReviewByIDRow, error) {
	row := q.db.QueryRow(ctx, getReviewByID, id)
	var i GetReviewByIDRow
	err := row.Scan(&i.ID, &i.Rating, &i.Comment)
	return i, err
}

const getUserReview = `-- name: GetUserReview :one
SELECT
    "id",
    "rating",
    "comment"
FROM
    "reviews"
WHERE
    "user_id" = $1
    AND "product_id" = $2
`

type GetUserReviewParams struct {
	UserID    string `json:"user_id"`
	ProductID string `json:"product_id"`
}

type GetUserReviewRow struct {
	ID      string  `json:"id"`
	Rating  int32   `json:"rating"`
	Comment *string `json:"comment"`
}

func (q *Queries) GetUserReview(ctx context.Context, arg GetUserReviewParams) (GetUserReviewRow, error) {
	row := q.db.QueryRow(ctx, getUserReview, arg.UserID, arg.ProductID)
	var i GetUserReviewRow
	err := row.Scan(&i.ID, &i.Rating, &i.Comment)
	return i, err
}

const insertReview = `-- name: InsertReview :one
INSERT INTO "reviews" ("user_id", "product_id", "rating", "comment")
    VALUES ($1, $2, $3, $4)
RETURNING
    "id"
`

type InsertReviewParams struct {
	UserID    string  `json:"user_id"`
	ProductID string  `json:"product_id"`
	Rating    int32   `json:"rating"`
	Comment   *string `json:"comment"`
}

func (q *Queries) InsertReview(ctx context.Context, arg InsertReviewParams) (string, error) {
	row := q.db.QueryRow(ctx, insertReview,
		arg.UserID,
		arg.ProductID,
		arg.Rating,
		arg.Comment,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateReview = `-- name: UpdateReview :one
UPDATE "reviews"
SET
    "rating" = $1,
    "comment" = $2,
    "updated_at" = NOW()
WHERE
    "user_id" = $3
    AND "product_id" = $4
RETURNING
    "id", "rating", "comment"
`

type UpdateReviewParams struct {
	Rating    int32   `json:"rating"`
	Comment   *string `json:"comment"`
	UserID    string  `json:"user_id"`
	ProductID string  `json:"product_id"`
}

type UpdateReviewRow struct {
	ID      string  `json:"id"`
	Rating  int32   `json:"rating"`
	Comment *string `json:"comment"`
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) (UpdateReviewRow, error) {
	row := q.db.QueryRow(ctx, updateReview,
		arg.Rating,
		arg.Comment,
		arg.UserID,
		arg.ProductID,
	)
	var i UpdateReviewRow
	err := row.Scan(&i.ID, &i.Rating, &i.Comment)
	return i, err
}
