// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRefreshToken = `-- name: DeleteRefreshToken :execrows
DELETE FROM "refresh_tokens"
WHERE "id" = $1
    AND "user_id" = $2
`

type DeleteRefreshTokenParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteRefreshToken(ctx context.Context, arg DeleteRefreshTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRefreshToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM "users"
WHERE "id" = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT
    id, user_id, hash_token, expiared_at
FROM
    "refresh_tokens"
WHERE
    "hash_token" = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, hashToken string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, hashToken)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HashToken,
		&i.ExpiaredAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    u."id",
    u."full_name",
    u."phone",
    u."birth",
    u."email",
    u."hash_password",
    COALESCE((
        SELECT
            JSON_AGG(JSON_BUILD_OBJECT('id', a."id", 'street_line_1', a."street_line_1", 'street_line_2', a."street_line_2", 'postal_code', a."postal_code", 'state', a."state", 'city', a."city", 'country', a."country", 'is_default', a."is_default"))
        FROM "addresses" a
        WHERE
            a."user_id" = u."id"), '[]'::json) AS "address"
FROM
    "users" u
WHERE
    u."email" = $1
GROUP BY
    u."id"
`

type GetUserByEmailRow struct {
	ID           string      `json:"id"`
	FullName     string      `json:"full_name"`
	Phone        string      `json:"phone"`
	Birth        pgtype.Date `json:"birth"`
	Email        string      `json:"email"`
	HashPassword string      `json:"-"`
	Address      interface{} `json:"address"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Birth,
		&i.Email,
		&i.HashPassword,
		&i.Address,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    u."id",
    u."full_name",
    u."phone",
    u."birth",
    u."email",
    COALESCE((
        SELECT
            JSON_AGG(JSON_BUILD_OBJECT('id', a."id", 'street_line_1', a."street_line_1", 'street_line_2', a."street_line_2", 'postal_code', a."postal_code", 'state', a."state", 'city', a."city", 'country', a."country", 'is_default', a."is_default"))
        FROM "addresses" a
        WHERE
            a."user_id" = u."id"), '[]'::json) AS "address"
FROM
    "users" u
WHERE
    u."id" = $1
GROUP BY
    u."id"
`

type GetUserByIDRow struct {
	ID       string      `json:"id"`
	FullName string      `json:"full_name"`
	Phone    string      `json:"phone"`
	Birth    pgtype.Date `json:"birth"`
	Email    string      `json:"email"`
	Address  interface{} `json:"address"`
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Birth,
		&i.Email,
		&i.Address,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO "refresh_tokens" ("user_id", "hash_token", "expiared_at")
    VALUES ($1, $2, $3)
`

type InsertRefreshTokenParams struct {
	UserID     string      `json:"user_id"`
	HashToken  string      `json:"hash_token"`
	ExpiaredAt pgtype.Date `json:"expiared_at"`
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken, arg.UserID, arg.HashToken, arg.ExpiaredAt)
	return err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO "users" ("full_name", "phone", "birth", "email", "hash_password")
    VALUES ($1, $2, $3, $4, $5)
RETURNING
    "id"
`

type InsertUserParams struct {
	FullName     string      `json:"full_name"`
	Phone        string      `json:"phone"`
	Birth        pgtype.Date `json:"birth"`
	Email        string      `json:"email"`
	HashPassword string      `json:"-"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (string, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.FullName,
		arg.Phone,
		arg.Birth,
		arg.Email,
		arg.HashPassword,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE
    "users"
SET
    "full_name" = COALESCE($2, "full_name"),
    "birth" = COALESCE($3, "birth"),
    "phone" = COALESCE($4, "phone"),
    "hash_password" = COALESCE($5, "hash_password"),
    "updated_at" = NOW()
WHERE
    "id" = $1
RETURNING
    id, full_name, birth, phone, email, hash_password, created_at, updated_at
`

type UpdateProfileParams struct {
	ID           string      `json:"id"`
	FullName     *string     `json:"full_name"`
	Birth        pgtype.Date `json:"birth"`
	Phone        *string     `json:"phone"`
	HashPassword *string     `json:"-"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.ID,
		arg.FullName,
		arg.Birth,
		arg.Phone,
		arg.HashPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Birth,
		&i.Phone,
		&i.Email,
		&i.HashPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
